### ISSUE TITLE
PSR-12 code standards

### ISSUE THREAD

**Issue by ismaail** [Zakarialabib/Mystock-Laravel-Liveiwre-Inventory-Pos#6]
please learn & adopt the [PSR-12](https://www.php-fig.org/psr/psr-12/) code standard in your code (all your PHP projects)

this will make it easier for other developers to review your code & contribute.

**Comment by ismaail** [comment]
looks like fixed in 9d5527856633d055ed025d43f9e56e01121f5168

**Comment by Zakarialabib** [comment]
yes it is, i will clean other project code as well, thank 👍
